# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nQ8f2nh-6K-yvJiJZV8lNPUYahQ9LbJ
"""

import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

data= pd.read_csv(r"C:\\Users\\Mery\\Downloads\\Students Social Media Addiction (1).csv")
print(data.head())

print(data.isnull().sum())

data.shape

data = data.drop_duplicates()
print(data)

data.shape

num_cols=data.select_dtypes(include=['int64','float64']).columns
cat_cols=data.select_dtypes(include=['object']).columns
num_imputer=SimpleImputer(strategy='mean')
cat_imputer=SimpleImputer(strategy='most_frequent')
data[num_cols]=num_imputer.fit_transform(data[num_cols])
data[cat_cols]=cat_imputer.fit_transform(data[cat_cols])
print(num_cols)
print(cat_cols)

def remove_ouliers(data,columns):
  Q1=data[columns].quanile(0.25)
  Q3=data[columns].quanile(0.75)
  IQR=Q3-Q1
  lower=Q1-1.5*IQR
  upper=Q3+1.5*IQR
  return data[(data[columns]>=lower) &(data[columns]<=upper)]
  data=remove_outliers(data,"Fare")

label_cols=['Gender']
le=LabelEncoder()
for col in label_cols:
  data[col]=le.fit_transform(data[col])

data=pd.get_dummies(data,columns=[col for col in cat_cols if col not in label_cols])

scaler=StandardScaler()
data[num_cols]=scaler.fit_transform(data[num_cols])

corr=data.corr()
plt.figure(dpi=130)
sns.heatmap(corr,annot=True,fmt='.2f',cmap='coolwarm')
plt.show()
print(corr['Addicted_Score'].sort_values(ascending=False))

# Calculate the median of the 'Addicted_Score' to define a threshold
median_addicted_score = data['Addicted_Score'].median()

# Create a new categorical Series: 'Addicted' if score is above median, 'Not Addicted' otherwise
addiction_categories = data['Addicted_Score'].apply(lambda x: 'Addicted' if x > median_addicted_score else 'Not Addicted')

# Get the counts of these two categories
addiction_counts = addiction_categories.value_counts()

# Plot the pie chart using these counts and their corresponding labels
plt.pie(addiction_counts, labels=addiction_counts.index, autopct='%.f%%', shadow=True)
plt.title('Social media Addiction')
plt.show()

X = data.drop('Addicted_Score', axis=1)

y = data['Addicted_Score']

X = StandardScaler().fit(X).transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size = 0.3, random_state = 4)

print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score
print("R² Score:", r2_score(y_test, y_pred))